const express = require("express");
const router = express.Router();
const controller = require("../../controllers/client/auth.controller");
const validate = require("../../validate/client/login.validate");
router.get("/login", controller.login);
router.post("/login", validate.login, controller.loginPost);
router.get("/register", controller.register);
router.post("/register", controller.registerPost);
router.get("/logout", controller.logout);
module.exports = router;
